### PR TITLE
Use simple version string ("X.Y.Z") for release versions. 

### PR DESCRIPTION
**Pull request by brickZA**
Keeps pypi happy. Minor doc fixes too

### CODE REVIEW

**Comment by ludwigschwardt** [comment]
Any chance of moving to katversion yet?

**Comment by brickZA** [comment]
@ludwigschwardt Happy to accept pull requests, so long as it doesn't break public installs :)

**Comment by ludwigschwardt** [comment]
katversion has just been open-sourced by the NRF a few days ago, so we are
good to go :-)

**Comment by bmerry** [comment]
On 20 June 2016 at 11:10, Ludwig Schwardt <notifications@github.com> wrote:

> katversion has just been open-sourced by the NRF a few days ago, so we are
> good to go :-)
>

Ludwig, can you put katversion on pypi, so that it will actually be found
by setup_requires='katversion'?

Bruce
-- 
Bruce Merry
Senior Science Processing Developer
SKA South Africa

**Pull request merged**
